#!/bin/sh
ln -sf ~/dotfiles/.agignore ~/.agignore
ln -sf ~/dotfiles/bin ~/bin
ln -sf ~/dotfiles/.config ~/.config
ln -sf ~/dotfiles/.dircolors ~/.dircolors
ln -sf ~/dotfiles/.gitconfig ~/.gitconfig
ln -sf ~/dotfiles/.gitignore_global ~/.gitignore_global
ln -sf ~/dotfiles/.gvimrc ~/.gvimrc
ln -sf ~/dotfiles/.mlterm ~/.mlterm
ln -sf ~/dotfiles/.sshrc.d ~/.sshrc.d
ln -sf ~/dotfiles/.vim ~/.vim
ln -sf ~/dotfiles/.vimrc ~/.vimrc
ln -sf ~/dotfiles/.Xresources ~/.Xresources
ln -sf ~/dotfiles/.zcompcustom  ~/.zcompcustom
ln -sf ~/dotfiles/.zfunctions ~/.zfunctions
ln -sf ~/dotfiles/.zimrc ~/.zimrc
ln -sf ~/dotfiles/.zkbd ~/.zkbd
ln -sf ~/dotfiles/.zlogin ~/.zlogin
ln -sf ~/dotfiles/.zprofile ~/.zprofile
ln -sf ~/dotfiles/.zshenv ~/.zshenv
ln -sf ~/dotfiles/.zshrc ~/.zshrc
